import { readFileSync, writeFileSync, existsSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SITEMAP_PATH = join(ROOT, 'dist', 'sitemap.xml')
const API_URL = 'https://hidden-water-ed9d.shop-backend-kitweb.workers.dev'
const SITE = 'https://kitcharoensampeng.com'
const LOCALES = ['th', 'en', 'zh', 'ja']
const MARKER = '<!-- DYNAMIC CATEGORY PAGES (auto-generated by append-sitemap.js) -->'

async function fetchCategories() {
  const response = await fetch(`${API_URL}/products`)
  if (!response.ok) {
    throw new Error(`Failed to fetch products: ${response.status}`)
  }

  const products = await response.json()
  return [...new Set(products.map((product) => product.category).filter(Boolean))].sort()
}

function buildCategoryUrlBlock(category, lang) {
  const segment = encodeURIComponent(category)
  const loc = `${SITE}/${lang}/catalog/${segment}`
  const defaultHref = `${SITE}/catalog/${segment}`

  return `  <url>
    <loc>${loc}</loc>
    <xhtml:link rel="alternate" hreflang="x-default" href="${defaultHref}" />
    <xhtml:link rel="alternate" hreflang="th" href="${SITE}/th/catalog/${segment}" />
    <xhtml:link rel="alternate" hreflang="en" href="${SITE}/en/catalog/${segment}" />
    <xhtml:link rel="alternate" hreflang="zh" href="${SITE}/zh/catalog/${segment}" />
    <xhtml:link rel="alternate" hreflang="ja" href="${SITE}/ja/catalog/${segment}" />
    <priority>0.9</priority>
  </url>`
}

function stripExistingDynamicSection(sitemap) {
  const markerIndex = sitemap.indexOf(MARKER)
  if (markerIndex === -1) {
    return sitemap
  }

  return sitemap.slice(0, markerIndex).trimEnd() + '\n\n'
}

async function main() {
  if (!existsSync(SITEMAP_PATH)) {
    throw new Error(`Missing ${SITEMAP_PATH}. Run "vite-ssg build" first.`)
  }

  const categories = await fetchCategories()
  let sitemap = readFileSync(SITEMAP_PATH, 'utf8')
  sitemap = stripExistingDynamicSection(sitemap)

  const blocks = [MARKER]

  for (const category of categories) {
    blocks.push(`  <!-- CATEGORY: ${category} -->`)
    for (const lang of LOCALES) {
      blocks.push(buildCategoryUrlBlock(category, lang))
    }
    blocks.push('')
  }

  if (!sitemap.includes('</urlset>')) {
    throw new Error('Invalid sitemap.xml: missing </urlset> tag.')
  }

  sitemap = sitemap.replace('</urlset>', `${blocks.join('\n')}</urlset>`)
  writeFileSync(SITEMAP_PATH, sitemap, 'utf8')

  console.log(
    `[append-sitemap] Appended ${categories.length} categories (${categories.length * LOCALES.length} URLs) to dist/sitemap.xml`
  )
}

main().catch((error) => {
  console.error('[append-sitemap] Failed:', error.message)
  process.exit(1)
})
