import { readFileSync, writeFileSync, existsSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import { absoluteUrl } from '../src/utils/siteUrl.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SITEMAP_PATH = join(ROOT, 'dist', 'sitemap.xml')
const API_URL = 'https://hidden-water-ed9d.shop-backend-kitweb.workers.dev'
const LOCALES = ['th', 'en', 'zh', 'ja']
const MARKER = '<!-- DYNAMIC CATEGORY PAGES (auto-generated by append-sitemap.js) -->'

async function fetchProducts() {
  const response = await fetch(`${API_URL}/products`)
  if (!response.ok) {
    throw new Error(`Failed to fetch products: ${response.status}`)
  }

  return await response.json()
}

// One path per product, under its own category — the same address the grid links
// to and vite-ssg prerenders, so the sitemap can't advertise a URL whose
// canonical points somewhere else.
function productPaths(products) {
  return products
    .filter((product) => product.slug && product.category)
    .map((product) => `${encodeURIComponent(product.category)}/${encodeURIComponent(product.slug)}`)
    .sort()
}

async function fetchProjectSlugs() {
  const response = await fetch(`${API_URL}/projects`)
  if (!response.ok) {
    throw new Error(`Failed to fetch projects: ${response.status}`)
  }

  const projects = await response.json()
  return projects.map((project) => project.slug).filter(Boolean)
}

// Same shape as a category entry, pointed at the editorial route.
function buildProjectUrlBlock(slug, lang) {
  const segment = encodeURIComponent(slug)
  const loc = absoluteUrl(`/${lang}/project/${segment}`)
  const defaultHref = absoluteUrl(`/en/project/${segment}`)

  return `  <url>
    <loc>${loc}</loc>
    <xhtml:link rel="alternate" hreflang="x-default" href="${defaultHref}" />
    <xhtml:link rel="alternate" hreflang="th" href="${absoluteUrl(`/th/project/${segment}`)}" />
    <xhtml:link rel="alternate" hreflang="en" href="${absoluteUrl(`/en/project/${segment}`)}" />
    <xhtml:link rel="alternate" hreflang="zh" href="${absoluteUrl(`/zh/project/${segment}`)}" />
    <xhtml:link rel="alternate" hreflang="ja" href="${absoluteUrl(`/ja/project/${segment}`)}" />
    <priority>0.7</priority>
  </url>`
}

// `path` is an already-encoded "<category>/<slug>" pair.
function buildProductUrlBlock(path, lang) {
  return `  <url>
    <loc>${absoluteUrl(`/${lang}/catalog/${path}`)}</loc>
    <xhtml:link rel="alternate" hreflang="x-default" href="${absoluteUrl(`/en/catalog/${path}`)}" />
    <xhtml:link rel="alternate" hreflang="th" href="${absoluteUrl(`/th/catalog/${path}`)}" />
    <xhtml:link rel="alternate" hreflang="en" href="${absoluteUrl(`/en/catalog/${path}`)}" />
    <xhtml:link rel="alternate" hreflang="zh" href="${absoluteUrl(`/zh/catalog/${path}`)}" />
    <xhtml:link rel="alternate" hreflang="ja" href="${absoluteUrl(`/ja/catalog/${path}`)}" />
    <priority>0.8</priority>
  </url>`
}

function buildCategoryUrlBlock(category, lang) {
  const segment = encodeURIComponent(category)
  const loc = absoluteUrl(`/${lang}/catalog/${segment}`)
  const defaultHref = absoluteUrl(`/en/catalog/${segment}`)

  return `  <url>
    <loc>${loc}</loc>
    <xhtml:link rel="alternate" hreflang="x-default" href="${defaultHref}" />
    <xhtml:link rel="alternate" hreflang="th" href="${absoluteUrl(`/th/catalog/${segment}`)}" />
    <xhtml:link rel="alternate" hreflang="en" href="${absoluteUrl(`/en/catalog/${segment}`)}" />
    <xhtml:link rel="alternate" hreflang="zh" href="${absoluteUrl(`/zh/catalog/${segment}`)}" />
    <xhtml:link rel="alternate" hreflang="ja" href="${absoluteUrl(`/ja/catalog/${segment}`)}" />
    <priority>0.9</priority>
  </url>`
}

function stripExistingDynamicSection(sitemap) {
  const markerIndex = sitemap.indexOf(MARKER)
  if (markerIndex === -1) {
    return sitemap
  }

  return sitemap.slice(0, markerIndex).trimEnd() + '\n\n'
}

async function main() {
  if (!existsSync(SITEMAP_PATH)) {
    throw new Error(`Missing ${SITEMAP_PATH}. Run "vite-ssg build" first.`)
  }

  const [products, projectSlugs] = await Promise.all([fetchProducts(), fetchProjectSlugs()])
  const categories = [...new Set(products.map((product) => product.category).filter(Boolean))].sort()
  const paths = productPaths(products)

  let sitemap = readFileSync(SITEMAP_PATH, 'utf8')
  sitemap = stripExistingDynamicSection(sitemap)

  const blocks = [MARKER]

  for (const category of categories) {
    blocks.push(`  <!-- CATEGORY: ${category} -->`)
    for (const lang of LOCALES) {
      blocks.push(buildCategoryUrlBlock(category, lang))
    }
    blocks.push('')
  }

  // Products are listed without a per-product comment: at ~150 rows the comments
  // would be most of the file.
  blocks.push(`  <!-- PRODUCTS (${paths.length}) -->`)
  for (const path of paths) {
    for (const lang of LOCALES) {
      blocks.push(buildProductUrlBlock(path, lang))
    }
  }
  blocks.push('')

  for (const slug of projectSlugs) {
    blocks.push(`  <!-- PROJECT: ${slug} -->`)
    for (const lang of LOCALES) {
      blocks.push(buildProjectUrlBlock(slug, lang))
    }
    blocks.push('')
  }

  if (!sitemap.includes('</urlset>')) {
    throw new Error('Invalid sitemap.xml: missing </urlset> tag.')
  }

  sitemap = sitemap.replace('</urlset>', `${blocks.join('\n')}</urlset>`)
  writeFileSync(SITEMAP_PATH, sitemap, 'utf8')

  const total = (categories.length + paths.length + projectSlugs.length) * LOCALES.length
  console.log(
    `[append-sitemap] Appended ${categories.length} categories + ${paths.length} products + ${projectSlugs.length} projects (${total} URLs) to dist/sitemap.xml`
  )
}

main().catch((error) => {
  console.error('[append-sitemap] Failed:', error.message)
  process.exit(1)
})
